set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports Rx_data]
set_property IOSTANDARD LVCMOS33 [get_ports tx_out]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports RECEIVED]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_out[0]}]
set_property PACKAGE_PIN V11 [get_ports {data_out[7]}]
set_property PACKAGE_PIN V12 [get_ports {data_out[6]}]
set_property PACKAGE_PIN V14 [get_ports {data_out[5]}]
set_property PACKAGE_PIN V15 [get_ports {data_out[4]}]
set_property PACKAGE_PIN T16 [get_ports {data_out[3]}]
set_property PACKAGE_PIN U14 [get_ports {data_out[2]}]
set_property PACKAGE_PIN T15 [get_ports {data_out[1]}]
set_property PACKAGE_PIN V16 [get_ports {data_out[0]}]

set_property PACKAGE_PIN V17 [get_ports check_store]
set_property PACKAGE_PIN R18 [get_ports check_sum]
set_property PACKAGE_PIN N14 [get_ports do_transmit]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN H17 [get_ports RECEIVED]
set_property PACKAGE_PIN V10 [get_ports reset]
set_property PACKAGE_PIN C4 [get_ports Rx_data]
set_property PACKAGE_PIN D4 [get_ports tx_out]
set_property IOSTANDARD LVCMOS33 [get_ports check_store]
set_property IOSTANDARD LVCMOS33 [get_ports do_transmit]
set_property IOSTANDARD LVCMOS33 [get_ports check_sum]

set_property IOSTANDARD LVCMOS33 [get_ports {data_count[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_count[0]}]
set_property PACKAGE_PIN U16 [get_ports data_count]

set_property PACKAGE_PIN V17 [get_ports {data_count[1]}]
set_property PACKAGE_PIN R18 [get_ports {data_count[0]}]

set_property PACKAGE_PIN U16 [get_ports {data_count[3]}]
set_property PACKAGE_PIN U17 [get_ports {data_count[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_count[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_count[2]}]
